/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc20PermitSol from "./draft-IERC20Permit.sol";
export type { draftIerc20PermitSol };
export type { ERC20Burnable } from "./ERC20Burnable";
export type { ERC20Capped } from "./ERC20Capped";
export type { ERC20Pausable } from "./ERC20Pausable";
export type { IERC20Metadata } from "./IERC20Metadata";
