/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20ExtendedUpgradeable__factory } from "./IERC20ExtendedUpgradeable__factory";
export { IMintable__factory } from "./IMintable__factory";
export { IlMagic__factory } from "./IlMagic__factory";
