/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ElvenAdventures } from "./ElvenAdventures";
export type { IElvenAdventures } from "./IElvenAdventures";
