/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ContractConstants,
  ContractConstantsInterface,
} from "../../../../contracts/upgradeable/utils/ContractConstants";

const _abi = [
  {
    inputs: [],
    name: "ADMIN_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "CONTRACT_ROLE",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ContractConstants__factory {
  static readonly abi = _abi;
  static createInterface(): ContractConstantsInterface {
    return new utils.Interface(_abi) as ContractConstantsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ContractConstants {
    return new Contract(address, _abi, signerOrProvider) as ContractConstants;
  }
}
