/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IProfessionStakingAvalanche__factory } from "./IProfessionStakingAvalanche__factory";
export { ProfessionStakingAvalanche__factory } from "./ProfessionStakingAvalanche__factory";
export { StakingRewardsClaimAvalanche__factory } from "./StakingRewardsClaimAvalanche__factory";
