/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProfessionStakingAvalanche,
  IProfessionStakingAvalancheInterface,
} from "../../../../../../contracts/upgradeable/npc/ProfessionStaking/Avalanche/IProfessionStakingAvalanche";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "isOwner",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IProfessionStakingAvalanche__factory {
  static readonly abi = _abi;
  static createInterface(): IProfessionStakingAvalancheInterface {
    return new utils.Interface(_abi) as IProfessionStakingAvalancheInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProfessionStakingAvalanche {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IProfessionStakingAvalanche;
  }
}
