/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20ExtendedUpgradeable } from "./IERC20ExtendedUpgradeable";
export type { IMintable } from "./IMintable";
export type { IlMagic } from "./IlMagic";
