/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProfessionStakingAvalanche } from "./IProfessionStakingAvalanche";
export type { ProfessionStakingAvalanche } from "./ProfessionStakingAvalanche";
export type { StakingRewardsClaimAvalanche } from "./StakingRewardsClaimAvalanche";
